# Generated by Django 5.2.5 on 2025-08-26 20:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='Nombre único del restaurante', max_length=255, unique=True, verbose_name='Nombre')),
                ('location', models.CharField(help_text='Dirección física del restaurante', max_length=255, verbose_name='Ubicación')),
                ('phone', models.CharField(blank=True, help_text='Número telefónico de contacto', max_length=16, validators=[core.validators.PhoneNumberValidator()], verbose_name='Teléfono')),
                ('description', models.TextField(blank=True, help_text='Descripción del restaurante y su oferta gastronómica', verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del restaurante', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['name'],
            },
        ),
    ]
