# Generated by Django 5.2.5 on 2025-08-26 20:44

import core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('name', models.CharField(help_text='Nombre del elemento del menú', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del plato', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en la moneda local', max_digits=8, validators=[core.validators.validate_positive_decimal], verbose_name='Precio')),
                ('category', models.CharField(choices=[('APPETIZER', 'Entrada'), ('MAIN', 'Plato Principal'), ('DESSERT', 'Postre'), ('DRINK', 'Bebida'), ('SIDE', 'Acompañamiento')], help_text='Categoría del elemento del menú', max_length=20, verbose_name='Categoría')),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Tiempo de preparación en minutos', validators=[core.validators.validate_preparation_time], verbose_name='Tiempo de preparación')),
            ],
            options={
                'verbose_name': 'Elemento del Menú',
                'verbose_name_plural': 'Elementos del Menú',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización')),
                ('order_number', models.CharField(blank=True, help_text='Número único de orden generado automáticamente', max_length=20, unique=True, verbose_name='Número de orden')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[core.validators.validate_positive_decimal], verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[core.validators.validate_positive_decimal], verbose_name='Impuestos')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[core.validators.validate_positive_decimal], verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_positive_decimal], verbose_name='Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PREPARING', 'En preparación'), ('READY', 'Lista'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Domicilio'), ('PICKUP', 'Recoger en tienda'), ('DINE_IN', 'Comer en restaurante')], default='DELIVERY', max_length=20, verbose_name='Tipo de orden')),
                ('delivery_address', models.TextField(blank=True, help_text='Dirección completa para entrega', verbose_name='Dirección de entrega')),
                ('delivery_notes', models.TextField(blank=True, help_text='Instrucciones especiales para la entrega', verbose_name='Notas especiales')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[core.validators.PhoneNumberValidator()], verbose_name='Teléfono de contacto')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo estimado de entrega')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora real de entrega')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[core.validators.validate_order_quantity], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[core.validators.validate_positive_decimal], verbose_name='Precio unitario')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones especiales')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización')),
                ('previous_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PREPARING', 'En preparación'), ('READY', 'Lista'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PREPARING', 'En preparación'), ('READY', 'Lista'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], max_length=20, verbose_name='Nuevo estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[core.validators.validate_rating], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional sobre la orden', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
